# Source - https://stackoverflow.com/a/67057478
# Posted by Pouyan Sepahvand, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-04, License - CC BY-SA 4.0

# -- FILE: pytest.ini (or tox.ini)
[pytest]
DJANGO_SETTINGS_MODULE = tamasy_server.settings
# -- recommended but optional:
python_files = tests.py test_*.py tests_*.py *_tests.py
