# Generated by Django 6.0.4 on 2026-04-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AP', 'Aperto'), ('CL', 'Completato')], default='AP', max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('severity', models.CharField(choices=[('LO', 'Bassa'), ('ME', 'Media'), ('HI', 'Alta')], default='LO', max_length=2, verbose_name='Severità')),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='FeatureTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('priority', models.CharField(choices=[('1', 'Bassa'), ('2', 'Normale'), ('3', 'Urgente')], default='2', max_length=1, verbose_name='Priorità')),
            ],
            bases=('tasks.task',),
        ),
    ]
