# Generated by Django 6.0.4 on 2026-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('T', 'Task'), ('B', 'Bug'), ('F', 'Feature')], default='T'),
        ),
    ]
