# Generated by Django 6.0.4 on 2026-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_to_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_reopen_task', 'Can reopen task')]},
        ),
    ]
