FROM python:3.14-slim-trixie

RUN apt-get update && apt-get install -y libpq-dev gcc iputils-ping dnsutils git postgresql-client nodejs npm && apt-get clean

RUN npm install -g @angular/cli bootstrap bootstrap-icons @angular-devkit/build-angular

WORKDIR /workspace

#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

# Keep the container running infinitely so VS Code can connect to it
CMD ["sleep", "infinity"]